In [1]:
import numpy as np

from scipy.io import loadmat
from sklearn.decomposition import PCA
from sklearn.metrics import accuracy_score

D:\Users\Alex\anaconda3\lib\site-packages\scipy\__init__.py:146: UserWarning: A NumPy version >=1.16.5 and <1.23.0 is required for this version of SciPy (detected version 1.23.1
  warnings.warn(f"A NumPy version >={np_minversion} and <{np_maxversion}"


# 1. Implement k-NN method

In [2]:
# calculate disntance between points. 
def euclidean_distance(point_a, point_b):
    sum = 0
    for elem_a, elem_b in zip(point_a,point_b):
        sum += (elem_a-elem_b)**2
    return np.sqrt(sum)

def get_closest_k_points(new_point, points_list, k=3):
    distances = []
    for elem in points_list:
        distance = euclidean_distance(new_point, elem)
        distances.append(distance) 
    #return np.argpartition(distances, k)[:k] # get the position of the closest k elements
    
    return (distances, np.argsort(distances)[:k])# get the position of the closest k elements

def knn_method(test_points, train_points, train_labels, k=3):
    count = 0
    predicted_labels = []
    for new_point in test_points:
        if (count%100 == 0):
            print(count)
        count+=1
        # get closest k elements
        _ , closest_elements = get_closest_k_points(new_point, train_points, k=k)
        #print(closest_elements)
        # get the lables of those k-closest elements
        label = []
        for closest_elem in closest_elements:
            label.append(train_labels[closest_elem][0])
        #prediction = np.bincount(label).argmax()# get most frequent value
        #print(label)
        prediction = max(set(label), key=label.count)# get most frequent value
        #print(prediction)
        predicted_labels.append(prediction)# save prediction
        #print()
    return np.array(predicted_labels)

# 2. Load train and test mat files, perform k-NN and report acuracy on the test dataset

In [3]:

# Open the model
train_dataset = loadmat('train_updated.mat')
#print(annots)

In [4]:
train_dataset

{'__header__': b'MATLAB 5.0 MAT-file, Platform: MACI64, Created on: Wed Oct 12 22:10:47 2022',
 '__version__': '1.0',
 '__globals__': [],
 'features': array([[-1.9087052e-01, -8.1624687e-01, -1.6324869e-01, ...,
         -1.7326276e-01, -3.3678705e-01,  1.4531960e+00],
        [-1.0689135e+00, -6.6361743e-01, -5.4769421e-01, ...,
          2.3691764e-01, -7.9150289e-01,  1.6607733e+00],
        [ 2.1004608e-01, -5.4553837e-01, -2.3526147e-01, ...,
          2.2105977e-01,  3.2690910e-01, -5.7891858e-01],
        ...,
        [ 3.0305445e-02,  1.2849410e-01, -3.2814008e-01, ...,
         -3.9511231e-01, -2.8412789e-04, -1.9695227e-01],
        [ 4.0498897e-02,  3.7712151e-01, -3.0760404e-01, ...,
         -4.9570936e-01, -7.3815003e-02, -1.6422004e-02],
        [ 1.5795332e-01,  5.9384692e-01, -1.9313660e-01, ...,
         -1.9358669e-01, -4.4733964e-02, -3.8367152e-01]], dtype=float32),
 'labels': array([[ 1],
        [ 1],
        [ 1],
        ...,
        [10],
        [10],
       

In [5]:
train_features = train_dataset['features']
train_labels = train_dataset['labels']
print(train_features.shape)
print(train_labels.shape)

(1123, 1000)
(1123, 1)


In [6]:

# Open the model
test_dataset = loadmat('test_updated.mat')
#print(annots)

In [7]:
test_dataset

{'__header__': b'MATLAB 5.0 MAT-file, Platform: MACI64, Created on: Sun Oct 16 11:43:39 2022',
 '__version__': '1.0',
 '__globals__': [],
 'features': array([[-0.1810047 , -0.3263064 ,  0.09900231, ...,  0.0896374 ,
          0.30170187, -0.315777  ],
        [-0.08604874, -0.24425426,  0.03491393, ...,  0.15105137,
          0.14930305, -0.50344443],
        [-0.02536274, -0.22994491,  0.0929625 , ...,  0.21274611,
          0.08147568, -0.5320467 ],
        ...,
        [-0.19452816,  0.09794576, -0.37737143, ..., -0.465474  ,
          0.04289951, -0.2871586 ],
        [-0.04896154,  0.2931249 , -0.28049102, ..., -0.2639083 ,
         -0.09265084, -0.3752439 ],
        [-0.09236805,  0.1781122 , -0.40881082, ..., -0.36157244,
          0.17647949, -0.36177444]], dtype=float32),
 'labels': array([[ 1],
        [ 1],
        [ 1],
        [ 1],
        [ 1],
        [ 1],
        [ 1],
        [ 1],
        [ 1],
        [ 1],
        [ 1],
        [ 1],
        [ 1],
        [ 1],
  

In [8]:
test_features = test_dataset['features']
test_labels = test_dataset['labels']
print(test_features.shape)
print(test_labels.shape)

(958, 1000)
(958, 1)


In [9]:
# call the method
predictions = knn_method(test_features, train_features, train_labels, k=5)
predictions

0
100
200
300
400
500
600
700
800
900


array([ 1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,
        1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,
        1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  6,  1,
        1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,
        1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,
        1,  1,  1,  1,  1,  1,  1,  2,  2,  2,  2,  2,  2,  2,  2,  2,  2,
        2,  2,  2,  2,  2,  2,  2,  2,  2,  2,  2,  2,  2,  2,  2,  1,  2,
        2,  2,  2,  2,  2,  2,  2,  2,  2,  2,  2,  2,  2,  2,  2,  2,  2,
        2,  2,  2,  2,  2,  2,  2,  2,  2,  2,  2,  2,  2,  2,  2,  2,  2,
        1,  2,  2,  2,  2,  2,  2,  2,  2,  2,  2,  2,  2,  2,  2,  2,  2,
        2,  2,  2,  2,  3,  3,  3,  3,  5,  3,  3,  3,  3,  3,  3,  3,  3,
        3,  3,  3,  3,  3,  3,  3,  3,  3,  3,  3,  3,  3,  3,  3,  3,  3,
        3,  3,  3,  3,  3,  3,  3,  3,  3,  3,  3,  3,  3,  3,  3,  3,  3,
        3,  3,  3,  3,  3

In [10]:
np.moveaxis(test_labels, 0, -1)[0]

array([ 1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,
        1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,
        1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,
        1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,
        1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,
        1,  1,  1,  1,  1,  1,  1,  2,  2,  2,  2,  2,  2,  2,  2,  2,  2,
        2,  2,  2,  2,  2,  2,  2,  2,  2,  2,  2,  2,  2,  2,  2,  2,  2,
        2,  2,  2,  2,  2,  2,  2,  2,  2,  2,  2,  2,  2,  2,  2,  2,  2,
        2,  2,  2,  2,  2,  2,  2,  2,  2,  2,  2,  2,  2,  2,  2,  2,  2,
        2,  2,  2,  2,  2,  2,  2,  2,  2,  2,  2,  2,  2,  2,  2,  2,  2,
        2,  2,  2,  2,  3,  3,  3,  3,  3,  3,  3,  3,  3,  3,  3,  3,  3,
        3,  3,  3,  3,  3,  3,  3,  3,  3,  3,  3,  3,  3,  3,  3,  3,  3,
        3,  3,  3,  3,  3,  3,  3,  3,  3,  3,  3,  3,  3,  3,  3,  3,  3,
        3,  3,  3,  3,  3

In [11]:
# Calculate Accuracy
acc = accuracy_score(np.moveaxis(test_labels, 0, -1)[0], predictions)

print("Accuracy: ", acc*100, "%")

Accuracy:  95.61586638830897 %


# 3. Reduce the dimensionality of features using PCA to low dimensions (e.g., 10, 3 ) and report the accuracy of the test datasets

In [12]:
pca = PCA(n_components=10)
pca.fit(train_features)

PCA(n_components=10)

In [13]:
pca_train_features = pca.transform(train_features)
pca_test_features = pca.transform(test_features)

In [14]:
# call the method
predictions = knn_method(pca_test_features, pca_train_features, train_labels, k=5)
predictions

0
100
200
300
400
500
600
700
800
900


array([ 1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  4,  1,  1,  1,
        1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,
        1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  6,  1,
        1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,
        1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,
        1,  1,  1,  1,  1,  1,  1,  2,  2,  2,  2,  2,  2,  2,  2,  2,  2,
        2,  2,  2,  2,  2,  2,  2,  2,  2,  2,  2,  2,  2,  2,  2,  4,  2,
        2,  2,  2,  2,  2,  2,  2,  2,  2,  2,  2,  2,  2,  2,  2,  2,  2,
        2,  2,  2,  2,  2,  2,  2,  2,  2,  2,  2,  2,  2,  2,  2,  2,  2,
        2,  2,  2,  2,  2,  2,  2,  2,  2,  2,  2,  2,  2,  2,  2,  2,  2,
        2,  2,  2,  2,  3,  3,  3,  3,  3,  3,  3,  3,  3,  3,  3,  3,  3,
        3,  3,  3,  3,  3,  3,  3,  3,  3,  3,  3,  3,  3,  3,  3,  3,  3,
        3,  3,  3,  3,  3,  3,  3,  3,  3,  3,  3,  3,  3,  3,  3,  3,  3,
        3,  3,  3,  3,  3

In [15]:
np.moveaxis(test_labels, 0, -1)[0]

array([ 1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,
        1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,
        1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,
        1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,
        1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,
        1,  1,  1,  1,  1,  1,  1,  2,  2,  2,  2,  2,  2,  2,  2,  2,  2,
        2,  2,  2,  2,  2,  2,  2,  2,  2,  2,  2,  2,  2,  2,  2,  2,  2,
        2,  2,  2,  2,  2,  2,  2,  2,  2,  2,  2,  2,  2,  2,  2,  2,  2,
        2,  2,  2,  2,  2,  2,  2,  2,  2,  2,  2,  2,  2,  2,  2,  2,  2,
        2,  2,  2,  2,  2,  2,  2,  2,  2,  2,  2,  2,  2,  2,  2,  2,  2,
        2,  2,  2,  2,  3,  3,  3,  3,  3,  3,  3,  3,  3,  3,  3,  3,  3,
        3,  3,  3,  3,  3,  3,  3,  3,  3,  3,  3,  3,  3,  3,  3,  3,  3,
        3,  3,  3,  3,  3,  3,  3,  3,  3,  3,  3,  3,  3,  3,  3,  3,  3,
        3,  3,  3,  3,  3

In [16]:
acc = accuracy_score(np.moveaxis(test_labels, 0, -1)[0], predictions)

print("Accuracy: ", acc*100, "%")

Accuracy:  95.4070981210856 %
